ptf $
BEGIN ATTRIBUTES
  NAME   RCHarray
  METHOD STEPWISE
  SFAC   1e-9
END ATTRIBUTES

BEGIN TIME 0
OPEN/CLOSE ../RCHrrca/00ss.dat   factor $rchss      $
END TIME 0

BEGIN TIME 1e9
CONSTANT 0.0
END TIME 1e9